In [2]:
import pandas as pd # needed for most operation
import numpy as np # needed for some array operations
from sklearn.model_selection import train_test_split
import pickle
pd.__version__

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn import tree
import matplotlib.pyplot as plt


In [10]:
data = pd.read_pickle("../data/IterImput")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
data.head(50)


0    1          2    3    4    5    6          7    8          9   \
0   1.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  0.0   9.000000   
1   3.0  1.0  10.000000  0.0  1.0  1.0  0.0   0.000000  1.0   5.000000   
2   1.0  1.0  10.000000  0.0  1.0  0.0  0.0   6.000000  1.0   8.000000   
3   5.0  1.0  10.000000  0.0  1.0  0.0  0.0   1.000000  1.0  10.000000   
4   1.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  1.0   7.000000   
5   5.0  1.0  10.000000  0.0  1.0  0.0  0.0   2.000000  1.0   6.000000   
6   5.0  1.0  10.000000  0.0  1.0  0.0  1.0  10.000000  1.0   9.000000   
7   5.0  1.0  10.000000  0.0  1.0  0.0  0.0   3.000000  0.0  10.000000   
8   5.0  1.0  10.000000  0.0  1.0  0.0  0.0   3.000000  1.0   5.000000   
9   5.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  0.0   5.000000   
10  5.0  1.0  10.000000  0.0  0.0  0.0  0.0   0.000000  1.0  10.000000   
11  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   6.000000  1.0   9.000000   
12  5.0  1.0   9.000000  0.0  1.0  0.0  0.0   2.000000  1.0  10.000000   
13  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   5.000000  1.0   7.000000   
14  1.0  1.0   8.000000  0.0  1.0  0.0  1.0   7.000000  1.0   5.000000   
15  2.0  1.0  10.000000  0.0  1.0  0.0  0.0   5.000000  1.0   9.000000   
16  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   2.000000  1.0   8.000000   
17  1.0  1.0   9.163588  0.0  1.0  0.0  0.0   2.119096  0.0   6.248206   
18  5.0  1.0   8.000000  0.0  1.0  0.0  0.0   1.000000  1.0   7.000000   
19  5.0  1.0   8.000000  0.0  1.0  0.0  0.0   3.000000  1.0   5.000000   
20  5.0  1.0  10.000000  0.0  0.0  0.0  0.0   0.000000  1.0  10.000000   
21  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  1.0   8.000000   
22  5.0  1.0  10.000000  0.0  1.0  0.0  1.0   6.000000  1.0   8.000000   
23  3.0  1.0   8.000000  0.0  1.0  0.0  0.0   6.000000  1.0   8.000000   
24  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   1.000000  0.0   3.000000   
25  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   7.000000  1.0   8.000000   
26  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  1.0   5.000000   
27  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   1.000000  1.0   6.000000   
28  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  1.0   7.000000   
29  1.0  1.0  10.000000  0.0  1.0  0.0  0.0   5.000000  1.0   2.000000   
30  5.0  1.0  10.000000  0.0  1.0  0.0  0.0  10.000000  0.0   7.861060   
31  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   2.000000  0.0   8.000000   
32  5.0  1.0   8.000000  0.0  1.0  0.0  0.0   0.000000  1.0   8.000000   
33  5.0  1.0   7.000000  0.0  1.0  0.0  1.0   7.000000  1.0  10.000000   
34  2.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  1.0  10.000000   
35  2.0  1.0   8.000000  0.0  1.0  0.0  0.0   4.000000  0.0   7.000000   
36  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  0.0   9.000000   
37  3.0  1.0  10.000000  0.0  1.0  0.0  0.0   4.000000  1.0   4.000000   
38  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  1.0   5.000000   
39  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  0.0   8.000000   
40  5.0  1.0   8.000000  0.0  0.0  0.0  0.0   0.000000  1.0   6.000000   
41  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   8.000000  1.0  10.000000   
42  5.0  1.0   7.000000  0.0  1.0  0.0  0.0   6.000000  1.0   8.000000   
43  5.0  1.0   8.000000  0.0  1.0  0.0  0.0   4.000000  1.0   2.000000   
44  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   0.000000  1.0   5.000000   
45  5.0  1.0  10.000000  0.0  1.0  0.0  0.0   1.000000  0.0   7.000000   
46  2.0  1.0   5.000000  0.0  0.0  0.0  0.0   2.000000  0.0   6.000000   
47  1.0  1.0  10.000000  0.0  1.0  0.0  0.0   7.000000  1.0   8.000000   
48  5.0  1.0  10.000000  0.0  0.0  0.0  1.0   0.000000  1.0  10.000000   
49  2.0  1.0  10.000000  0.0  1.0  0.0  0.0   2.000000  1.0  10.000000   

           10         11         12         13   14   15        16   17   18  \
0   10.000000   0.000000   7.000000   7.000000  7.0  0.0  1.000000  1.0  1.0   
1    0.000000   7.000000  10.000000  10.000000  5.0  1.0  1.000000  1.

In [6]:
data.columns
#X = data.loc[:, data.columns != 'Treatment']
#y = data['Treatment']

X = data.loc[:, data.columns != 0]
y = data[0]
# print(y)


In [9]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model_tree = DecisionTreeClassifier(max_depth=10)
model_tree = model_tree.fit(X_train, y_train)
plt.figure(figsize=(30,30)) # set plot size (denoted in inches)
#tree.plot_tree(model_tree, fontsize=8)
#plt.show()

#AIXO FERHO AMB TRAINING O TEST SET? DESPRES PODEM CROSS VALIDAR
y_predict = model_tree.predict(X_test)
print(classification_report(y_test,y_predict))

#tree_cv = cross_val_score(model_tree,X_train,y=Y_train, cv=10)
#np.mean(tree_cv)

print(confusion_matrix(y_test, y_predict))
#print(classification_report(y_test, y_predict))
#accuracy_score(y_true, y_pred, *, normalize=True, sample_weight=None)

#importances = model_tree.feature_importances_


              precision    recall  f1-score   support

         1.0       0.52      0.46      0.49       148
         2.0       0.14      0.13      0.14        31
         3.0       0.00      0.00      0.00        14
         5.0       0.42      0.53      0.47       114

    accuracy                           0.43       307
   macro avg       0.27      0.28      0.27       307
weighted avg       0.42      0.43      0.42       307

[[68 15  3 62]
 [12  4  0 15]
 [ 6  1  0  7]
 [44  8  2 60]]


<Figure size 2160x2160 with 0 Axes>