In [50]:
import pandas as pd # needed for most operation
import numpy as np # needed for some array operations
from sklearn.model_selection import train_test_split
import pickle
pd.__version__

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn import tree
import matplotlib.pyplot as plt


In [51]:
data = pd.read_pickle("../data/imputedData_1")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
data.head(100)


Treatment Fever Duration_of_pain  Sick_leave  Earlier_hospitalization  \
0            1   1.0             10.0           0                        1   
1            3   1.0             10.0           0                        1   
2            1   1.0             10.0           0                        1   
3            5   1.0             10.0           0                        1   
4            1   1.0             10.0           0                        1   
5            5   1.0             10.0           0                        1   
6            5   1.0             10.0           0                        1   
7            5   1.0             10.0           0                        1   
8            5   1.0             10.0           0                        1   
10           5   1.0             10.0           0                        1   
11           5   1.0             10.0           0                        0   
12           5   1.0             10.0           0                        1   
13           5   1.0              9.0           0                        1   
14           5   1.0             10.0           0                        1   
15           1   1.0              8.0           0                        1   
16           2   1.0             10.0           0                        1   
17           5   1.0             10.0           0                        1   
18           1   1.0             10.0           0                        1   
19           5   1.0              8.0           0                        1   
20           5   1.0              8.0           0                        1   
21           5   1.0             10.0           0                        0   
22           5   1.0             10.0           0                        1   
24           5   1.0             10.0           0                        1   
25           3   1.0              8.0           0                        1   
26           5   1.0             10.0           0                        1   
27           5   1.0             10.0           0                        1   
28           5   1.0             10.0           0                        1   
29           5   1.0             10.0           0                        1   
30           5   1.0             10.0           0                        1   
31           1   1.0             10.0           0                        1   
32           5   1.0             10.0           0                        1   
33           5   1.0             10.0           0                        1   
34           5   1.0              8.0           0                        1   
35           5   1.0              7.0           0                        1   
36           2   1.0             10.0           0                        1   
37           2   1.0              8.0           0                        1   
38           5   1.0             10.0           0                        1   
39           3   1.0             10.0           0                        1   
40           5   1.0             10.0           0                        1   
41           5   1.0             10.0           0                        1   
42           5   1.0              8.0           0                        0   
43           5   1.0             10.0           0                        1   
44           5   1.0              7.0           0                        1   
45           5   1.0              8.0           0                        1   
46           5   1.0             10.0           0                        1   
47           5   1.0             10.0           0                        1   
48           2   1.0              5.0           0                        0   
49           1   1.0             10.0           0                        1   
50           5   1.0             10.0           0                        0   
52           2   1.0             10.0           0                        1   
54           5   1.0       

In [52]:
data.columns
X = data.loc[:, data.columns != 'Treatment']
y = data['Treatment']
print(y)


0       1
1       3
2       1
3       5
4       1
5       5
6       5
7       5
8       5
10      5
11      5
12      5
13      5
14      5
15      1
16      2
17      5
18      1
19      5
20      5
21      5
22      5
24      5
25      3
26      5
27      5
28      5
29      5
30      5
31      1
32      5
33      5
34      5
35      5
36      2
37      2
38      5
39      3
40      5
41      5
42      5
43      5
44      5
45      5
46      5
47      5
48      2
49      1
50      5
52      2
54      5
55      5
56      5
57      1
58      5
59      5
60      1
61      5
62      5
63      3
64      5
65      5
66      1
67      2
68      1
69      5
70      1
71      5
72      5
73      2
74      5
75      1
76      3
77      5
78      5
79      1
80      5
81      2
82      1
83      5
84      3
85      5
86      5
87      1
88      1
89      5
90      1
91      1
92      5
93      5
94      5
95      1
96      5
97      5
98      2
99      5
100     5
101     5
102     5
103     5


In [59]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model_tree = DecisionTreeClassifier(max_depth=5)
model_tree = model_tree.fit(X_train, y_train)
plt.figure(figsize=(30,30)) # set plot size (denoted in inches)
#tree.plot_tree(model_tree, fontsize=8)
#plt.show()

#AIXO FERHO AMB TRAINING O TEST SET? DESPRES PODEM CROSS VALIDAR
y_predict = model_tree.predict(X_train)
print(classification_report(y_train,y_predict))

#tree_cv = cross_val_score(model_tree,X_train,y=Y_train, cv=10)
#np.mean(tree_cv)

print(confusion_matrix(y_train, y_predict))
#print(classification_report(y_test, y_predict))
#accuracy_score(y_true, y_pred, *, normalize=True, sample_weight=None)

#importances = model_tree.feature_importances_


              precision    recall  f1-score   support

           1       0.56      0.60      0.58       511
           2       0.67      0.02      0.03       129
           3       0.45      0.18      0.25        51
           5       0.56      0.68      0.61       535

    accuracy                           0.55      1226
   macro avg       0.56      0.37      0.37      1226
weighted avg       0.56      0.55      0.52      1226

[[307   0   6 198]
 [ 60   2   3  64]
 [ 16   0   9  26]
 [170   1   2 362]]


<Figure size 2160x2160 with 0 Axes>